import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { Router } from '@angular/router';
import { finalize } from 'rxjs/operators';
import { ParametroDebitoService } from './parametro-debito.service';
import { ToastModule } from 'primeng/toast';
// import Swal from 'sweetalert2';
import { CommonService } from '@/pages/service/commonService';
import { TabsModule } from 'primeng/tabs';
import { InputNumberModule } from 'primeng/inputnumber';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { ConfirmationService, MenuItem, MessageService } from 'primeng/api';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { ButtonModule } from 'primeng/button';
import { DatePickerModule } from 'primeng/datepicker';
import { DividerModule } from 'primeng/divider';
import { DialogService } from 'primeng/dynamicdialog';
import { FileUploadModule } from 'primeng/fileupload';
import { InputTextModule } from 'primeng/inputtext';
import { MessageModule } from 'primeng/message';
import { TableModule } from 'primeng/table';
import { MenuModule } from 'primeng/menu';
import { TooltipModule } from 'primeng/tooltip';
import { ParametroDebitoAddComponent } from './parametro-debito-add/parametro-debito-add.component';
import { ParametroDebitoEditComponent } from './parametro-debito-edit/parametro-debito-edit.component';
import { ConfirmDialogModule } from 'primeng/confirmdialog';

@Component({
    selector: 'app-parametro-debito',
    templateUrl: './parametro-debito.component.html',
    styleUrls: ['./parametro-debito.component.scss'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [ConfirmDialogModule, TooltipModule, TabsModule, MenuModule, DividerModule, InputNumberModule, DatePickerModule, TableModule, MessageModule, ToastModule, ButtonModule, FileUploadModule, ReactiveFormsModule, CommonModule, InputTextModule, AutoCompleteModule],
    providers: [MessageService, DialogService, ConfirmationService],
})
export class ParametroDebitoComponent implements OnInit {
    data: any[] = [];
    rows = 10;
    rowsPerPageOptions: any[] = [];
    loading: boolean = false;
    constructor(
        private dialog: DialogService,
        private parametroDebitoService: ParametroDebitoService,
        private commonService: CommonService,
        private toastr: MessageService,
        private router: Router,
        private confirmationService: ConfirmationService,
    ) { }

    ngOnInit(): void {
        this.getParametros();
    }

    getParametros() {
        this.loading = true;
        var resp = {
            "codigo": 0,
            "mensaje": "OK",
            "data": [
                {
                    "codParametro": 46,
                    "codTabla": 1,
                    "nomTabla": "TIPO_PERSONA_LEGAL",
                    "codTablaElemento": 1,
                    "desElemento": "TIPO PERSONA LEGAL",
                    "valCadCorto": "NATURAL",
                    "valCadLargo": "PERSONA NATURAL",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T18:43:46.785",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 47,
                    "codTabla": 1,
                    "nomTabla": "TIPO_PERSONA_LEGAL",
                    "codTablaElemento": 2,
                    "desElemento": "TIPO PERSONA LEGAL",
                    "valCadCorto": "JURIDICA",
                    "valCadLargo": "PERSONA JURIDICA",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T18:45:10.415",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 48,
                    "codTabla": 2,
                    "nomTabla": "TIPO_PAGO_EHOST",
                    "codTablaElemento": 1,
                    "desElemento": "TIPO PAGO EHOST",
                    "valCadCorto": "",
                    "valCadLargo": "CHEQUE",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T18:46:51.177",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-09-22T18:55:57.882"
                },
                {
                    "codParametro": 49,
                    "codTabla": 2,
                    "nomTabla": "TIPO_PAGO_EHOST",
                    "codTablaElemento": 2,
                    "desElemento": "TIPO PAGO EHOST",
                    "valCadCorto": "",
                    "valCadLargo": "TRANSFERENCIA",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T18:58:00.414",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 50,
                    "codTabla": 3,
                    "nomTabla": "TIPO_MONEDA_TRAMA",
                    "codTablaElemento": 1,
                    "desElemento": "TIPO MONEDA TRAMA",
                    "valCadCorto": "PEN",
                    "valCadLargo": "SOLES",
                    "valNumEntero": 604,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:01:14.974",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-09-22T19:05:44.3"
                },
                {
                    "codParametro": 51,
                    "codTabla": 3,
                    "nomTabla": "TIPO_MONEDA_TRAMA",
                    "codTablaElemento": 2,
                    "desElemento": "TIPO MONEDA TRAMA",
                    "valCadCorto": "USD",
                    "valCadLargo": "DOLARES",
                    "valNumEntero": 840,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:07:18.188",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 54,
                    "codTabla": 4,
                    "nomTabla": "BANCO_EHOST",
                    "codTablaElemento": 3,
                    "desElemento": "BANCO EHOST",
                    "valCadCorto": "",
                    "valCadLargo": "INTERBANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:09:53.377",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 57,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 1,
                    "desElemento": "DEBITO_CHQ_IBK_PEN",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "INTERBANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:14:36.032",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:55:04.658"
                },
                {
                    "codParametro": 58,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 2,
                    "desElemento": "DEBITO_CHQ_IBK_USD",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "INTERBANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:14:56.42",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:55:16.3"
                },
                {
                    "codParametro": 59,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 3,
                    "desElemento": "DEBITO_TRANSF_IBK_USD",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "INTERBANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:15:49.336",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:55:29.578"
                },
                {
                    "codParametro": 60,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 4,
                    "desElemento": "DEBITO_TRANSF_IBK_PEN",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "INTERBANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:16:15.78",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:55:40.248"
                },
                {
                    "codParametro": 61,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 5,
                    "desElemento": "DEBITO_TRANSF_SCTB_USD",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "SCOTIABANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:16:38.238",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:55:51.291"
                },
                {
                    "codParametro": 62,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 6,
                    "desElemento": "DEBITO_TRANSF_SCTB_PEN",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "SCOTIABANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:16:50.821",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:02.436"
                },
                {
                    "codParametro": 63,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 7,
                    "desElemento": "DEBITO_CHQ_SCTB_USD",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "SCOTIABANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:01.792",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:13.177"
                },
                {
                    "codParametro": 64,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 8,
                    "desElemento": "DEBITO_CHQ_SCTB_PEN",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "SCOTIABANK",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:10.852",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:24.861"
                },
                {
                    "codParametro": 65,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 9,
                    "desElemento": "DEBITO_CHQ_BBVA_USD",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "BBVA_CONTINENTAL",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:22.596",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:35.118"
                },
                {
                    "codParametro": 66,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 10,
                    "desElemento": "DEBITO_CHQ_BBVA_PEN",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "BBVA_CONTINENTAL",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:31.535",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:45.357"
                },
                {
                    "codParametro": 67,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 11,
                    "desElemento": "DEBITO_TRANSF_BBVA_USD",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "BBVA_CONTINENTAL",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:40.015",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:56:54.576"
                },
                {
                    "codParametro": 68,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 12,
                    "desElemento": "DEBITO_TRANSF_BBVA_PEN",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "BBVA_CONTINENTAL",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:17:53.861",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:57:04.857"
                },
                {
                    "codParametro": 69,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 13,
                    "desElemento": "DEBITO_CHQ_BCP_USD",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "BCP",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:18:02.796",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:57:20.117"
                },
                {
                    "codParametro": 70,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 14,
                    "desElemento": "DEBITO_CHQ_BCP_PEN",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "BCP",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:18:12.783",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:57:33.968"
                },
                {
                    "codParametro": 71,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 15,
                    "desElemento": "DEBITO_TRANSF_BCP_USD",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "BCP",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:18:20.783",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:57:48.649"
                },
                {
                    "codParametro": 72,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 16,
                    "desElemento": "DEBITO_TRANSF_BCP_PEN",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "BCP",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:18:39.915",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:58:01.766"
                },
                {
                    "codParametro": 73,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 17,
                    "desElemento": "DEBITO_CHQ_FOH_USD",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "FINANCIERA_OH",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:18:56.239",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:58:16.307"
                },
                {
                    "codParametro": 74,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 18,
                    "desElemento": "DEBITO_CHQ_FOH_PEN",
                    "valCadCorto": "CHEQUE",
                    "valCadLargo": "FINANCIERA_OH",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:19:05.205",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:58:28.773"
                },
                {
                    "codParametro": 75,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 19,
                    "desElemento": "DEBITO_TRANSF_FOH_USD",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "FINANCIERA_OH",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:19:14.712",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:58:40.802"
                },
                {
                    "codParametro": 76,
                    "codTabla": 5,
                    "nomTabla": "MOTIVO_DESEMBOLSO",
                    "codTablaElemento": 20,
                    "desElemento": "DEBITO_TRANSF_FOH_PEN",
                    "valCadCorto": "TRANSF",
                    "valCadLargo": "FINANCIERA_OH",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-22T19:29:07.854",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-14T16:58:53.02"
                },
                {
                    "codParametro": 81,
                    "codTabla": 6,
                    "nomTabla": "TIPO_RETENCION",
                    "codTablaElemento": 1,
                    "desElemento": "TIPO RETENCION",
                    "valCadCorto": null,
                    "valCadLargo": "SUNAT",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-26T12:10:49.571",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 82,
                    "codTabla": 6,
                    "nomTabla": "TIPO_RETENCION",
                    "codTablaElemento": 2,
                    "desElemento": "TIPO RETENCION",
                    "valCadCorto": null,
                    "valCadLargo": "JUZGADO",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-26T12:11:11.778",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 83,
                    "codTabla": 6,
                    "nomTabla": "TIPO_RETENCION",
                    "codTablaElemento": 3,
                    "desElemento": "TIPO RETENCION",
                    "valCadCorto": null,
                    "valCadLargo": "SAT",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-26T12:11:39.41",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 84,
                    "codTabla": 6,
                    "nomTabla": "TIPO_RETENCION",
                    "codTablaElemento": 4,
                    "desElemento": "TIPO RETENCION",
                    "valCadCorto": null,
                    "valCadLargo": "MUNICIPIOS",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-26T12:11:59.578",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 85,
                    "codTabla": 6,
                    "nomTabla": "TIPO_RETENCION",
                    "codTablaElemento": 5,
                    "desElemento": "TIPO RETENCION",
                    "valCadCorto": null,
                    "valCadLargo": "OTROS",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-26T12:12:30.527",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 86,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 1,
                    "desElemento": "Recarga con Pago Efectivo - Local",
                    "valCadCorto": "ABONO",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:49:37.05",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 87,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 2,
                    "desElemento": "Abono Promocional",
                    "valCadCorto": "ABONO",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:51:53.129",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 88,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 3,
                    "desElemento": "Ajuste para abonar capital",
                    "valCadCorto": "ABONO",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:52:25.343",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 89,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 4,
                    "desElemento": "Ajuste para retirar capital",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:53:33.671",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-11T10:05:13.3"
                },
                {
                    "codParametro": 90,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 5,
                    "desElemento": "Pago de Servicios",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:55:28.677",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 91,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 6,
                    "desElemento": "Recarga de celular",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:55:50.841",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 92,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 7,
                    "desElemento": "Pago de compra realizada en Web Intralot (AgoraWeb)",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:56:16.43",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 93,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 8,
                    "desElemento": "Pago de compra realizada en Web Cineplanet (AgoraWeb)",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:56:37.227",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 94,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 9,
                    "desElemento": "P2P-Retiro en BBR para depositar en Ahorros IziPay Mismo Titular",
                    "valCadCorto": "CARGO",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:57:23.218",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 95,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 10,
                    "desElemento": "Recarga con Tarjeta de Débito",
                    "valCadCorto": "ABONO",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:57:52.603",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 96,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 11,
                    "desElemento": "Recarga Agora Shop (para el Shopper)",
                    "valCadCorto": "ABONO",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-09-29T10:58:11.866",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 97,
                    "codTabla": 8,
                    "nomTabla": "PLAZO_MAXIMO_CONSULTA_AUTORIZACIONES",
                    "codTablaElemento": 1,
                    "desElemento": "Plazo Máximo Consulta Autorizaciones",
                    "valCadCorto": null,
                    "valCadLargo": null,
                    "valNumEntero": 60,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:30:53.449",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 98,
                    "codTabla": 9,
                    "nomTabla": "ESTADO_CONFIRMACION_AUTORIZACION",
                    "codTablaElemento": 1,
                    "desElemento": "TODOS",
                    "valCadCorto": "ALL",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:49:19.819",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-06T09:51:29.586"
                },
                {
                    "codParametro": 99,
                    "codTabla": 9,
                    "nomTabla": "ESTADO_CONFIRMACION_AUTORIZACION",
                    "codTablaElemento": 2,
                    "desElemento": "PENDIENTES",
                    "valCadCorto": "PENDING",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:50:22.808",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2022-10-06T09:51:18.77"
                },
                {
                    "codParametro": 100,
                    "codTabla": 9,
                    "nomTabla": "ESTADO_CONFIRMACION_AUTORIZACION",
                    "codTablaElemento": 3,
                    "desElemento": "CONFIRMADOS",
                    "valCadCorto": "CONFIRMED",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:50:59.502",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 101,
                    "codTabla": 10,
                    "nomTabla": "TIPO_RED_AUTORIZACION",
                    "codTablaElemento": 1,
                    "desElemento": "TODOS",
                    "valCadCorto": "ALL",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:55:15.73",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 102,
                    "codTabla": 10,
                    "nomTabla": "TIPO_RED_AUTORIZACION",
                    "codTablaElemento": 2,
                    "desElemento": "VISA",
                    "valCadCorto": "VISA",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:55:38.445",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 103,
                    "codTabla": 10,
                    "nomTabla": "TIPO_RED_AUTORIZACION",
                    "codTablaElemento": 3,
                    "desElemento": "BBR",
                    "valCadCorto": "BBR",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:55:52.858",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 104,
                    "codTabla": 10,
                    "nomTabla": "TIPO_RED_AUTORIZACION",
                    "codTablaElemento": 4,
                    "desElemento": "IZIPAY",
                    "valCadCorto": "Izipay",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:56:14.872",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 105,
                    "codTabla": 10,
                    "nomTabla": "TIPO_RED_AUTORIZACION",
                    "codTablaElemento": 5,
                    "desElemento": "APP",
                    "valCadCorto": "AP",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-10-06T09:56:36.222",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 106,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 1,
                    "desElemento": "COMPRA/PAGO",
                    "valCadCorto": "00",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:55:17.667",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 107,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 2,
                    "desElemento": "RETIRO/AVANCE EN EFECTIVO",
                    "valCadCorto": "01",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:55:58.173",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 108,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 3,
                    "desElemento": "ABONO DE DINERO",
                    "valCadCorto": "20",
                    "valCadLargo": "ABONO",
                    "valNumEntero": 20,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:56:26.743",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 109,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 4,
                    "desElemento": "TRANSFERENCIA RETIRO",
                    "valCadCorto": "02",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:56:48.268",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 110,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 5,
                    "desElemento": "TRANSFERENCIA ABONO",
                    "valCadCorto": "21",
                    "valCadLargo": "ABONO",
                    "valNumEntero": 21,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:57:09.422",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 111,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 6,
                    "desElemento": "RETENCIONES",
                    "valCadCorto": "22",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 22,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:58:33.427",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 112,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 7,
                    "desElemento": "LIBERACION DE RETENCION",
                    "valCadCorto": "23",
                    "valCadLargo": "ABONO",
                    "valNumEntero": 23,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:58:53.334",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 113,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 8,
                    "desElemento": "PAGO RETENCION BENEFICIARIO",
                    "valCadCorto": "24",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 24,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:59:18.388",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 114,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 9,
                    "desElemento": "PAGO FALLECIMIENTO A BENEFICIARIO",
                    "valCadCorto": "25",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 25,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T10:59:43.373",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 115,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 10,
                    "desElemento": "AJUSTE DE RETIRO",
                    "valCadCorto": "26",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 26,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T11:00:07.017",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 116,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 11,
                    "desElemento": "AJUSTE DE ABONO",
                    "valCadCorto": "27",
                    "valCadLargo": "ABONO",
                    "valNumEntero": 27,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2022-10-13T11:00:21.79",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 117,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 1,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000010",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-02T18:46:55.858",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 118,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 2,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000101",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-02T18:47:44.982",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 119,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 3,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000102",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-02T18:48:03.053",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 120,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 4,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000103",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-02T18:49:20.316",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 121,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 5,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000104",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-02T18:49:47.822",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2023-06-16T17:22:55.058"
                },
                {
                    "codParametro": 122,
                    "codTabla": 13,
                    "nomTabla": "PAIS_ISO",
                    "codTablaElemento": 1,
                    "desElemento": "United States of America (the)",
                    "valCadCorto": "USA",
                    "valCadLargo": null,
                    "valNumEntero": 840,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2022-11-03T16:10:18.207",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 123,
                    "codTabla": 13,
                    "nomTabla": "PAIS_ISO",
                    "codTablaElemento": 2,
                    "desElemento": "Peru",
                    "valCadCorto": "PER",
                    "valCadLargo": null,
                    "valNumEntero": 604,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2022-11-03T16:11:42.44",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 124,
                    "codTabla": 14,
                    "nomTabla": "PLAZO_MAXIMO_CONSULTA_HISTORIAL_TARJETA_BOTONERA",
                    "codTablaElemento": 1,
                    "desElemento": "PLAZO MÁXIMO CONSULTA HISTORIAL TARJETA BOTONERA",
                    "valCadCorto": null,
                    "valCadLargo": null,
                    "valNumEntero": 60,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2022-11-10T10:20:38.997",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 125,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 1,
                    "desElemento": "Aplicar a movimientos por tolerancia (Anulación trans. original)",
                    "valCadCorto": "01",
                    "valCadLargo": "Aplicar a movimientos por tolerancia",
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T10:39:21.868",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:02:58.089011"
                },
                {
                    "codParametro": 126,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 2,
                    "desElemento": "Pase a pérdida",
                    "valCadCorto": "02",
                    "valCadLargo": "Pase a pérdida",
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T10:39:50.333",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-05-16T12:01:32.245992"
                },
                {
                    "codParametro": 127,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 3,
                    "desElemento": "Contracargo",
                    "valCadCorto": "03",
                    "valCadLargo": "Contracargo",
                    "valNumEntero": 3,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T10:40:28.914",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:03:51.292908"
                },
                {
                    "codParametro": 128,
                    "codTabla": 16,
                    "nomTabla": "ESTADO_TRX_OBS",
                    "codTablaElemento": 1,
                    "desElemento": "ABIERTO",
                    "valCadCorto": "01",
                    "valCadLargo": "ABIERTO",
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T10:41:05.107",
                    "usuarioModificacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaModificacion": "2023-01-24T11:48:26.395"
                },
                {
                    "codParametro": 129,
                    "codTabla": 16,
                    "nomTabla": "ESTADO_TRX_OBS",
                    "codTablaElemento": 2,
                    "desElemento": "CERRADO",
                    "valCadCorto": "02",
                    "valCadLargo": "CERRADO",
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T10:41:50.918",
                    "usuarioModificacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaModificacion": "2023-01-24T11:48:42.338"
                },
                {
                    "codParametro": 130,
                    "codTabla": 17,
                    "nomTabla": "TIPO_ANULACION_TRX_OBS",
                    "codTablaElemento": 1,
                    "desElemento": "TOTAL",
                    "valCadCorto": "TOTAL",
                    "valCadLargo": "TOTAL",
                    "valNumEntero": 1,
                    "valNumDecimal": 1,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T15:46:51.284",
                    "usuarioModificacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaModificacion": "2023-01-24T15:49:01.73"
                },
                {
                    "codParametro": 131,
                    "codTabla": 17,
                    "nomTabla": "TIPO_ANULACION_TRX_OBS",
                    "codTablaElemento": 2,
                    "desElemento": "PARCIAL",
                    "valCadCorto": "PARCIAL",
                    "valCadLargo": "PARCIAL",
                    "valNumEntero": 2,
                    "valNumDecimal": 2,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-01-24T15:49:53.14",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 132,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 4,
                    "desElemento": "Ajuste abono manual",
                    "valCadCorto": "04",
                    "valCadLargo": "Ajuste abono manual",
                    "valNumEntero": 4,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Roosevelt.Orbegozo@somosoh.pe",
                    "fechaCreacion": "2023-05-23T17:39:25.45",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:04:12.333785"
                },
                {
                    "codParametro": 133,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 6,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000014",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-06-16T17:06:45.965",
                    "usuarioModificacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2023-06-16T17:23:07.496"
                },
                {
                    "codParametro": 134,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 7,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000014",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-06-16T18:07:38.264",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 135,
                    "codTabla": 12,
                    "nomTabla": "CODIGO_COMERCIO_AJUSTE",
                    "codTablaElemento": 8,
                    "desElemento": "CODIGO COMERCIO AJUSTE",
                    "valCadCorto": null,
                    "valCadLargo": "100000000000014",
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-06-16T18:08:25.267",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 136,
                    "codTabla": 18,
                    "nomTabla": "TIPO_DOCUMENTO",
                    "codTablaElemento": 1,
                    "desElemento": "DOCUMENTO NACIONAL DE IDENTIDAD",
                    "valCadCorto": "DNI",
                    "valCadLargo": null,
                    "valNumEntero": 1,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-16T18:09:56.729",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 137,
                    "codTabla": 18,
                    "nomTabla": "TIPO_DOCUMENTO",
                    "codTablaElemento": 2,
                    "desElemento": "CARNET DE EXTRANJERIA",
                    "valCadCorto": "CE",
                    "valCadLargo": null,
                    "valNumEntero": 2,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-16T18:10:54.773",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 138,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 1,
                    "desElemento": "BANCO DE CREDITO DEL PERU",
                    "valCadCorto": "002",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:45:28.977",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 139,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 2,
                    "desElemento": "INTERBANK",
                    "valCadCorto": "003",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:45:51.539",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 140,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 3,
                    "desElemento": "CITIBANK DEL PERÚ",
                    "valCadCorto": "007",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:46:15.215",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 141,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 4,
                    "desElemento": "SCOTIABANK PERÚ",
                    "valCadCorto": "009",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:46:36.814",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 142,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 5,
                    "desElemento": "BBVA PERÚ",
                    "valCadCorto": "011",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:47:05.188",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 143,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 6,
                    "desElemento": "BANCO DE LA NACIÓN",
                    "valCadCorto": "018",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:47:31.429",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 144,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 7,
                    "desElemento": "BANCO DE COMERCIO",
                    "valCadCorto": "023",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:47:53.593",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 145,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 8,
                    "desElemento": "BANCO PICHINCHA",
                    "valCadCorto": "035",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:48:17.494",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 146,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 9,
                    "desElemento": "BANBIF",
                    "valCadCorto": "038",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:48:38.383",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 147,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 10,
                    "desElemento": "CREDISCOTIA FINANCIERA",
                    "valCadCorto": "043",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:49:03.899",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 148,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 11,
                    "desElemento": "MI BANCO",
                    "valCadCorto": "049",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:50:00.281",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 149,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 12,
                    "desElemento": "AGROBANCO",
                    "valCadCorto": "051",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:50:24.43",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 150,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 13,
                    "desElemento": "BANCO GNB PERÚ",
                    "valCadCorto": "053",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:50:49.197",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 151,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 14,
                    "desElemento": "BANCO FALABELLA PERÚ",
                    "valCadCorto": "054",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:51:13.283",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 152,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 15,
                    "desElemento": "BANCO RIPLEY",
                    "valCadCorto": "055",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:51:31.556",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 153,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 16,
                    "desElemento": "BANCO SANTANDER PERÚ",
                    "valCadCorto": "056",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:51:59.23",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 154,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 17,
                    "desElemento": "BANCO ALFIN",
                    "valCadCorto": "058",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:52:16.692",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 155,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 18,
                    "desElemento": "ICBC PERÚ BANK",
                    "valCadCorto": "060",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:52:31.927",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 156,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 19,
                    "desElemento": "COMPARTAMOS FINANCIERA",
                    "valCadCorto": "091",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:52:51.541",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 157,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 20,
                    "desElemento": "FINANCIERA EFECTIVA",
                    "valCadCorto": "096",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:53:16.315",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 158,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 21,
                    "desElemento": "CAJA METROPOLITANA",
                    "valCadCorto": "800",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:53:37.74",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 159,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 22,
                    "desElemento": "CMAC PIURA",
                    "valCadCorto": "801",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:54:08.892",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 160,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 23,
                    "desElemento": "CMAC TRUJILLO",
                    "valCadCorto": "802",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:54:28.858",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 161,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 24,
                    "desElemento": "CMAC AREQUIPA",
                    "valCadCorto": "803",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:54:46.561",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 162,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 25,
                    "desElemento": "CMAC SULLANA",
                    "valCadCorto": "805",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:55:36.88",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 163,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 26,
                    "desElemento": "CMAC CUZCO",
                    "valCadCorto": "806",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:56:22.039",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 164,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 27,
                    "desElemento": "CMAC HUANCAYO",
                    "valCadCorto": "808",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:56:39.854",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 165,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 28,
                    "desElemento": "CMAC ICA",
                    "valCadCorto": "809",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:56:56.278",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 166,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 29,
                    "desElemento": "CMAC MAYNAS",
                    "valCadCorto": "811",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:57:10.084",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 167,
                    "codTabla": 19,
                    "nomTabla": "BANCO_TIN_INTEROP",
                    "codTablaElemento": 30,
                    "desElemento": "CMAC TACNA",
                    "valCadCorto": "813",
                    "valCadLargo": null,
                    "valNumEntero": 0,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "BLUP.Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2023-08-21T09:57:24.93",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 170,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 5,
                    "desElemento": "Desestimar",
                    "valCadCorto": "05",
                    "valCadLargo": "Desestimar",
                    "valNumEntero": 5,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2024-05-30T10:05:27.396",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:04:29.14376"
                },
                {
                    "codParametro": 171,
                    "codTabla": 7,
                    "nomTabla": "TRANSACCION_ORIGINAL_AJUSTE",
                    "codTablaElemento": 12,
                    "desElemento": "Cargo Comisión envío EECC físico",
                    "valCadCorto": "CARGO",
                    "valCadLargo": "Comisión por envío EECC físico",
                    "valNumEntero": 2,
                    "valNumDecimal": 20,
                    "estParametro": 1,
                    "usuarioCreacion": "Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2024-05-30T10:42:23.685",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2024-06-19T18:13:44.469"
                },
                {
                    "codParametro": 172,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 6,
                    "desElemento": "Confirmar movimiento",
                    "valCadCorto": "06",
                    "valCadLargo": "Confirmar movimiento",
                    "valNumEntero": 6,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2024-07-09T11:53:01.165",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:04:56.438149"
                },
                {
                    "codParametro": 173,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 7,
                    "desElemento": "Aplicar a movimientos (Trans. no encontrada en el procesador)",
                    "valCadCorto": "07",
                    "valCadLargo": "Aplicar a movimientos",
                    "valNumEntero": 7,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Esteban.Castillo@somosoh.pe",
                    "fechaCreacion": "2024-07-09T11:53:48.999",
                    "usuarioModificacion": "Esteban.Castillo@somosoh.pe",
                    "fechaModificacion": "2025-03-12T10:05:55.665688"
                },
                {
                    "codParametro": 174,
                    "codTabla": 11,
                    "nomTabla": "OPERATION_CODE",
                    "codTablaElemento": 1,
                    "desElemento": "INTEROPERABILIDAD RETIRO",
                    "valCadCorto": "28",
                    "valCadLargo": "CARGO",
                    "valNumEntero": 28,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "Benjy.Collantes@somosoh.pe",
                    "fechaCreacion": "2024-07-10T09:08:34.757",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                },
                {
                    "codParametro": 176,
                    "codTabla": 15,
                    "nomTabla": "TIPO_SOLUCION_TRX_OBS",
                    "codTablaElemento": 8,
                    "desElemento": "Aplicar a movimientos por tolerancia (Anulación trans. original)",
                    "valCadCorto": "08",
                    "valCadLargo": "Aplicar a movimientos por tolerancia",
                    "valNumEntero": 8,
                    "valNumDecimal": 0,
                    "estParametro": 1,
                    "usuarioCreacion": "HRCP.Segundo.Ccarhuas@somosoh.pe",
                    "fechaCreacion": "2025-07-31T16:06:07.077175",
                    "usuarioModificacion": null,
                    "fechaModificacion": null
                }
            ]
        };
        if (resp['codigo'] == 0) {
            this.data = resp['data'];
            this.data.sort((a, b) => a.nomTabla.localeCompare(b.nomTabla));
            this.rowsPerPageOptions = this.commonService.getRowsPerPageOptions(this.rows, this.data.length);
        } else if (resp['codigo'] == -1) {
            this.toastr.add({ severity: 'error', summary: 'Error getParametros', detail: resp['mensaje'] });
        }
        this.loading = false;
        // this.parametroDebitoService.getParametros().pipe(
        //     finalize(() => {
        //         this.loading = false;
        //     })
        // ).subscribe((resp: any) => {
        //     if (resp['codigo'] == 0) {
        //         this.data = resp['data'];
        //         this.data.sort((a, b) => a.nomTabla.localeCompare(b.nomTabla));
        //         this.rowsPerPageOptions = this.commonService.getRowsPerPageOptions(this.rows, this.data.length);
        //     } else if (resp['codigo'] == -1) {
        //         this.toastr.add({ severity: 'error', summary: 'Error getParametros', detail: resp['mensaje'] });
        //     }
        // }, (_error) => {
        //     this.toastr.add({ severity: 'error', summary: 'Error getParametros', detail: 'Error en el servicio de obtener parámetros' });
        // })
    }

    menuItems: any[] = [];
    onButtonClick(event: Event, rowData: any, menu: any) {
        this.menuItems = this.getMenuItems(rowData);
        menu.toggle(event);
    }
    // ✅ Este método devuelve el menú según la fila + rol
    getMenuItems(rowData: any, menu?: any): MenuItem[] {
        const items: MenuItem[] = [];
        items.push({
            label: 'Editar',
            icon: 'pi pi-pencil',
            command: () => {
                setTimeout(() => {
                    this.goToEditParametro(rowData)
                    menu?.hide();  // cerrar directamente
                }, 5);
            }
        });
        items.push({
            label: 'Eliminar',
            icon: 'pi pi-ban',
            command: () => this.deleteParametro(rowData)
        });

        return items;
    }

    deleteParametro(parametro: any) {     
        this.confirmationService.confirm({
            header: 'Eliminar parámetro',
            message: '¿Estás seguro de querer realizar esta acción?',
            icon: 'pi pi-exclamation-triangle',
             rejectButtonProps: {
                label: 'Cancel',
                severity: 'secondary',
                outlined: true,
            },
            acceptButtonProps: {
                label: 'Aceptar',
            },
            accept: () => {
                this.parametroDebitoService.deleteParametro(parametro.codParametro).subscribe(
                    (res: any) => {
                        if (res['codigo'] == 0) {
                            const index = this.data.findIndex((d: any) => d.codParametro === parametro.codParametro);
                            this.data.splice(index, 1);
                            this.toastr.add({ severity: 'success', summary: '', detail: 'Parámetro eliminado' });
                            //this.toastr.success('Parámetro eliminado');
                        } else {
                            this.toastr.add({ severity: 'error', summary: 'Error deleteParametro', detail: 'Error en el servicio de inactivar parámetro' });
                        }
                    }
                )
            },
            reject: () => {
                //this.messageService.add({ severity: 'error', summary: 'Rejected', detail: 'You have rejected' });
            }
        });       
    }

    goToAddParametro() {
        const dialogRef = this.dialog.open(ParametroDebitoAddComponent, {
            header: 'Registrar parámetro de débito',
            width: '50vw',
            modal: true,
            styleClass: 'header-modal',
            dismissableMask: true,  // permite cerrar al hacer click fuera
            breakpoints: {
                '960px': '75vw',
                '640px': '90vw'
            },
            // data: {
            //     codParametro: parametro.codParametro,
            // }
        });
    }
    goToEditParametro(parametro: any) {
        const dialogRef = this.dialog.open(ParametroDebitoEditComponent, {
            header: 'Editando parámetro de débito',
            width: '50vw',
            modal: true,
            styleClass: 'header-modal',
            dismissableMask: true,  // permite cerrar al hacer click fuera
            breakpoints: {
                '960px': '75vw',
                '640px': '90vw'
            },
            data: {
                codParametro: parametro.codParametro,
            }
        });

        //this.router.navigate(['/apps/mantenimiento/parametro/debito/edit/' + parametro.codParametro]);
    }
}